# Generated by Django 4.2.7 on 2024-02-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('remote_game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('bracket', models.TextField()),
                ('games', models.ManyToManyField(to='remote_game.remotegame')),
            ],
        ),
    ]
