version: '3'

### Services ###
services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
      args:
        - DOMAIN
        - CERT_PATH
        - CERT_KEY_PATH
    restart: always
    volumes:
      - frontend_data:/code
    ports:
      - "443:443"
    networks:
      - transcendencenet
  frontend:
    build: ./requirements/frontend
    depends_on:
      - backend
    # restart: always
    volumes:
      - frontend_data:/code
    ports:
      - "8080:8080" # needed for development server only
    networks:
      - transcendencenet
  backend:
    build: ./requirements/backend
    # this command writes the necessary things to the database, creates a superuser for the admin panel and starts the server
    # I think later we should import the database for django from a file (to PostgreSQL-container) instead of creating it here
    command: bash -c "python manage.py migrate && python manage.py createsuperuser --noinput && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db # wait for db to be ready
    environment:
      - DOMAIN=$DOMAIN
      - DJANGO_SUPERUSER_USERNAME=$DJANGO_SUPERUSER_USERNAME
      - DJANGO_SUPERUSER_PASSWORD=$DJANGO_SUPERUSER_PASSWORD
      - DJANGO_SUPERUSER_EMAIL=$DJANGO_SUPERUSER_EMAIL
    restart: always
    volumes:
      - backend_data:/code
    ports:
      - "8000:8000" # not needed ! nginx redirects all /api requests to backend
    networks:
      - transcendencenet
  db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    networks:
      - transcendencenet
  adminer:
    image: adminer
    depends_on:
      - db 
    restart: always
    networks:
      - transcendencenet

### Networks ###
networks:
  transcendencenet:

### Volumes ###
volumes:
  frontend_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $FRONTEND_DATA_PATH
  backend_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $BACKEND_DATA_PATH
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $DB_DATA_PATH
