version: '3'

### Services ###
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
      args:
        - DOMAIN
        - CERT_PATH
        - CERT_KEY_PATH
    env_file:
      - .env
    restart: always
    volumes:
      - nginx_data:/etc/nginx/conf.d
    networks:
      - transcendencenet
    ports:
      - "443:443"
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: requirements/frontend/Dockerfile
      args:
        - DOMAIN
        - CERT_PATH
        - CERT_KEY_PATH
    restart: always
    volumes:
      - frontend_data:/code
    networks:
      - transcendencenet
  backend:
    container_name: backend
    build: ./requirements/backend
    env_file:
      - .env
    restart: always
    volumes:
      - backend_data:/code
    networks:
      - transcendencenet
  db:
    container_name: db
    image: postgres
    env_file:
      - .env
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - transcendencenet
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    networks:
      - transcendencenet

### Networks ###
networks:
  transcendencenet:

### Volumes ###
volumes:
  frontend_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $FRONTEND_DATA_PATH
  backend_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $BACKEND_DATA_PATH
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $DB_DATA_PATH
  nginx_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $NGINX_DATA_PATH
