version: '3'

### Services ###
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        - DOMAIN
        - CERT_PATH
        - CERT_KEY_PATH
    env_file:
      - .env
    restart: always
    volumes:
      - ${PWD}/nginx/conf/nginx.conf:/etc/nginx/nginx.conf.d/nginx.conf
      - static_django_files:/static
    ports:
      - "443:443"

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - DOMAIN
        - CERT_PATH
        - CERT_KEY_PATH
    restart: always
    volumes:
      - ${PWD}/frontend/app:/code

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - CERT_PATH
        - CERT_KEY_PATH
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    volumes:
      - ${PWD}/backend/files:/code
      - static_django_files:/static
    ports:
      - 8000:8000

  db:
    container_name: db
    image: postgres:15.5-bookworm
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always

volumes:
  postgres:
  static_django_files: