version: '3'

### Services ###
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${CERT_PATH}:/etc/nginx/ssl/inception.crt
      - ${CERT_KEY_PATH}:/etc/nginx/ssl/inception.key
      - static_django_files:/static
      - ./media:/media
    ports:
      - "80:80"
      - "443:443"

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - DOMAIN
        - CERT_PATH
        - CERT_KEY_PATH
    env_file:
      - .env_frontend
    restart: always
    volumes:
      - ./frontend/app:/code

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - CERT_PATH
        - CERT_KEY_PATH
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    volumes:
      - ./backend/files:/code
      - static_django_files:/static
      - ./media:/media
    # ports:
    #   - 8000:8000

  db:
    container_name: db
    image: postgres:15.5-bookworm
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always

volumes:
  postgres:
  static_django_files: