version: '3'

### Services ###
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        - DOMAIN
        - CERT_PATH
        - CERT_KEY_PATH
    env_file:
      - .env
    restart: always
    volumes:
      - ${PWD}/nginx/conf/nginx.conf:/etc/nginx/nginx.conf.d/nginx.conf
    ports:
      - "443:443"

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - DOMAIN
        - CERT_PATH
        - CERT_KEY_PATH
    restart: always
    volumes:
      - ${PWD}/frontend/app:/code

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - .env
    restart: always
    volumes:
      - ${PWD}/backend/files:/code

  db:
    container_name: db
    image: postgres
    env_file:
      - .env
    restart: always
    volumes:
      - ${PWD}/postgres:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always

