# Generated by Django 4.2.7 on 2023-11-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_games'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Players',
        ),
    ]
