# Generated by Django 4.2.7 on 2023-11-29 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_rename_users_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pong.players'),
        ),
    ]
