# Generated by Django 4.2.7 on 2023-11-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_player'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Games',
        ),
        migrations.RenameModel(
            old_name='Player',
            new_name='Players',
        ),
    ]
