# Generated by Django 4.2.7 on 2023-11-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0007_rename_game_games_rename_player_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='description',
            new_name='descriptions',
        ),
    ]
