# Generated by Django 4.2.7 on 2023-11-30 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0008_rename_description_players_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='descriptions',
            new_name='description',
        ),
    ]
