# Generated by Django 4.2.7 on 2023-11-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0009_rename_descriptions_players_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='player1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='player2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
