# Generated by Django 4.2.7 on 2023-11-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0010_games_player1_games_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='players',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
