# Generated by Django 4.2.7 on 2023-12-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
