# Generated by Django 4.2.7 on 2024-02-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotegame',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remotegame',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
