# Generated by Django 4.2.7 on 2024-01-15 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_game', '0002_remotegame_numberofhitsp1_remotegame_numberofhitsp2'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotegame',
            name='gameDuration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
