# Generated by Django 4.2.7 on 2024-02-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_game', '0003_alter_remotegame_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotegame',
            name='gameDuration',
        ),
        migrations.AddField(
            model_name='remotegame',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
