# Generated by Django 4.2.7 on 2024-02-02 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remote_game', '0004_remove_remotegame_gameduration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotegame',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_lost', to=settings.AUTH_USER_MODEL),
        ),
    ]
