# Generated by Django 4.2.7 on 2024-02-02 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_game', '0005_remotegame_loser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remotegame',
            old_name='numberofHitsP1',
            new_name='numberOfHitsP1',
        ),
        migrations.RenameField(
            model_name='remotegame',
            old_name='numberofHitsP2',
            new_name='numberOfHitsP2',
        ),
    ]
