# Generated by Django 4.2.7 on 2024-02-02 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_game', '0006_rename_numberofhitsp1_remotegame_numberofhitsp1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remotegame',
            old_name='numberOfHitsP1',
            new_name='pointsP1',
        ),
        migrations.RenameField(
            model_name='remotegame',
            old_name='numberOfHitsP2',
            new_name='pointsP2',
        ),
    ]
