# Generated by Django 4.2.7 on 2023-12-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
