# Generated by Django 4.2.7 on 2023-12-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customuser_mobile_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chat_online',
            field=models.BooleanField(default=False),
        ),
    ]
