# Generated by Django 4.2.7 on 2024-01-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_chat_online'),
        ('api', '0004_alter_customuser_profile_pic'),
    ]

    operations = [
    ]
