# Generated by Django 4.2.7 on 2024-01-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20240115_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.FileField(blank=True, default='profilepic/default.jpeg', null=True, upload_to='profilepic'),
        ),
    ]
