# Generated by Django 4.2.7 on 2024-01-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='games_played',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='statistics',
            name='mmr',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='statistics',
            name='ranking',
            field=models.IntegerField(default=1),
        ),
    ]
