# Generated by Django 4.2.7 on 2024-01-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_message_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
